### ISSUE TITLE
Creating a graph using adjacency list

### ISSUE THREAD

**Issue by Vyom-Yadav** [SkienaBook/Algorithm-Design-Manual-Programs-V3#4]
This may be a typo or lack of understanding. I posted this on SO.

From https://stackoverflow.com/q/76985913/15412365:

> I am following Skiena's Algorithm Design Manual v3.
> 
> I have seen a few questions stating that there are certain **typos** in the book, and I am not sure whether this is one or just because I cannot understand it.
> 
> Consider the following:
> 
> ```C
> typedef struct edgenode {
>     int y;                   /* adjacency info */
>     int weight;              /* edge weight, if any */
>     struct edgenode *next;   /* next edge in list */
> } edgenode;
> 
> typedef struct {
>     edgenode *edges[MAXV+1];  /* adjacency info */
>     int degree[MAXV+1];       /* outdegree of each vertex */
>     int nvertices;            /* number of vertices in the graph */
>     int nedges;               /* number of edges in the graph */
>     int directed;             /* is the graph directed? */
> } graph;
> 
> void insert_edge(graph *g, int x, int y, bool directed) {
>     edgenode *p;        /* temporary pointer */
> 
>     p = malloc(sizeof(edgenode));    /* allocate edgenode storage */
> 
>     p->weight = 0;
>     p->y = y;
>     p->next = g->edges[x];
> 
>     g->edges[x] = p;    /* insert at head of list */
> 
>     g->degree[x]++;
> 
>     if (!directed) {
>         insert_edge(g, y, x, true);
>     } else {
>         g->nedges++;
>     }
> }
> ```
> 
> As far as I understand, `void insert_edge(graph *g, int x, int y, bool directed)` connects two nodes at array index `x` and `y` by adding them to `edges` array.
> 
> The following snippet confuses me:
> 
> ```C
> p->y = y;
> p->next = g->edges[x];
> 
> g->edges[x] = p;    /* insert at head of list */
> ```
> 
> How is this working? Suppose my input is `x = 3, y = 4`, and this is the first input.
> 
> I would expect something like `3 -> 4` for a directed graph.
> 
> 1. `p->y = y;` makes perfect sense, the adjacent of `x` is `y`.
> 2. `p->next = g->edges[x];` But the `edges` array is initialized to null. Won't this make `3.next == NULL` instead of `3.next == 4`?
> 3. `g->edges[x] = p;` What? `edges[x] == x Node`, this confuses me.
> 
> The complete code can be found at [graph.c](https://github.com/SkienaBook/Algorithm-Design-Manual-Programs-V3/blob/main/graph.c) and [graph.h](https://github.com/SkienaBook/Algorithm-Design-Manual-Programs-V3/blob/main/graph.h).
> 
> I think `p.next = y;` somehow and `y.next = NULL` as of now i.e. the first insertion. Maybe it's my rusty C but need some help on this.

@SkienaBook Can you please clarify this?

Thanks!

**Comment by Vyom-Yadav** [comment]
I understood it.

**Comment by SkienaBook** [comment]
Vyom,

Is all now clear and correct with the book?

Or is there a problem you can explain to me?

Thanks
Steven Skiena

**Comment by Vyom-Yadav** [comment]
It is all clear sir. Thanks a lot for the book!

**Comment by SkienaBook** [comment]
Thanks
STeven Skiena
